### ISSUE TITLE
change es6 object method definitions in main.js to es5 style for compatibility

### ISSUE THREAD

**Issue by wwkc** [jgebhardt/react-for-atom#1]
The issue with the es6 object methods stops browsers like phantomjs 1.9 from parsing this file unless it is transformed in a build step for a project that uses it.

**Comment by wwkc** [comment]
https://github.com/jgebhardt/react-for-atom/pull/2

**Comment by wwkc** [comment]
FYI this was from trying to use https://facebook.github.io/fixed-data-table/

**Comment by jgebhardt** [comment]
Closed in afed82e7e411c561547de2067f04b09e577e7d37.
