### ISSUE TITLE
Different versions of react-for-atom used in different packages

### ISSUE THREAD

**Issue by sadovnychyi** [jgebhardt/react-for-atom#10]
I've hyperclick installed which uses react-for-atom @ 0.14.3 and go-debug which uses 0.14.7. Since they are not compatible in terms of API and since you use global variable -- go-debug come up using 0.14.3. 

https://github.com/lloiser/go-debug/issues/8

At least you could namespace the global variable to be version specific. Something like `atom.__DO_NOT_ACCESS_React_Singleton_v_0_14_7` would work I'm sure.

**Comment by ssorallen** [comment]
The "hyperclick" package has been superseded by the "nuclide" package. If you'd like to use Hyperclick, install the "nuclide" package and disable the features you don't need.

**Comment by sadovnychyi** [comment]
Still, there's could be more packages using different versions of react-for-atom, and as for me, it should be fixed.

**Comment by Osmose** [comment]
We're seeing similar issues in advanced-open-file: https://github.com/Osmose/advanced-open-file/issues/104

If you can't have more than one React global on the page, then having multiple versions of React on the same page seems like it wouldn't work either. It seems like this package is just straight-up broken for anyone besides nuclide.

**Comment by mythmon** [comment]
At the very least, this package should detect when two different versions of React are trying to be loaded and throw an easy to understand error. Now there are very hard to debug errors that occur only when certain combinations of packages are installed.

**Comment by zertosh** [comment]
We've deprecated this project.
