### ISSUE TITLE
Is it possible to use packages such as react-redux that depend on React?

### ISSUE THREAD

**Issue by mbylstra** [jgebhardt/react-for-atom#16]
Or would you have to fork them to import `react-for-atom` instead of `react`?

I'm using react-redux and redux-form, but I'm getting a lot of `Minified React error #119` (http://facebook.github.io/react/docs/error-decoder.html?invariant=119) errors, and I suspect react-redux or redux-form might be causing them, but I'm not sure.

Is there a way to run the Atom package in some kind of dev mode to get a better error message from React?

**Comment by zertosh** [comment]
It's a problem we're aware of. Recent versions of React can co-exist with other instances of React in the same environment so long as you don't try to nest components from the different instances. Given this, we've decided to deprecate this project. See 48933a01da0c5bad722e6566d82bcae79ed718ce.
