### ISSUE TITLE
Working Example

### ISSUE THREAD

**Issue by ShMcK** [jgebhardt/react-for-atom#3]
Do you have any working examples of a basic package setup using `react-for-atom`?

**Comment by jgebhardt** [comment]
Hey, you could check out some of the Nuclide UI packages which make use of `react-for-atom`, e.g.
https://github.com/facebook/nuclide/tree/master/pkg/nuclide/ui/radiogroup/lib

Generally speaking, you can simply use it in the same manner as you would use regular React.

**Comment by ShMcK** [comment]
Thanks. I tried using the example, but I keep running into the same error when I try to `React.render()` a component inside of Atom.

```
Invariant Violation: _registerComponent(...): Target container is not a DOM element.
```

Do you know of any existing Atom packages using `react-for-atom`?  I'd love to take a look at a code example.

**Comment by ShMcK** [comment]
I found a working solution: [atom-react-starter](https://github.com/amitmtrn/atom-react-starter), and demo example: [atom-ftp-editor](https://github.com/amitmtrn/atom-ftp-editor). 

You were largely correct, I believe the issue was a conflict with `space-pen`.
